######################################################################
# Automatically generated by qmake (2.01a) Sze ápr. 22 10:20:00 2020
######################################################################

QT += widgets

TEMPLATE = app
TARGET = Sejtauto
INCLUDEPATH += .

# Input
HEADERS += sejtablak.h sejtszal.h
SOURCES += main.cpp sejtablak.cpp sejtszal.cpp
